#!/usr/bin/env bash
set -e

# Environement variables
: ${DATABASE_URL:="mysql://root:root@db/drupal"}
: ${DATABASE_DUMP:="/var/backups/database.sql"}
: ${SMTP_HOST:="mail:1025"}
: ${SITE_NAME:="Drupal Website"}
: ${SITE_UUID:=$(sed -n -e '/uuid:/ s/.*\: *//p' ./config/d8/sync/system.site.yml)}
: ${PRIVATE_FILES:=""}
: ${DEFAULT_CONTENT:=""}

: ${PHPUNIT_DEFAULT_GROUP:=""}
: ${SYMFONY_DEPRECATIONS_HELPER:="weak"}
: ${SIMPLETEST_DB:="$DATABASE_URL"}
: ${SIMPLETEST_BASE_URL:="http://127.0.0.1:8888"}

# Script variables
SCRIPT_NAME=$(basename $0)
CONFIG_DIR="../config/d8/sync/"
DATABASE_USER=$(a=${DATABASE_URL#*//}; echo ${a%:*})
DATABASE_NAME=${DATABASE_URL##*/}
DATABASE_HOST=$(a=${DATABASE_URL#*@}; echo ${a%/*})
DRUPAL_INSTALLED=$(drush sql-query "SELECT * FROM users_field_data where uid = 1" >/dev/null 2>&1 && echo 1 || echo 0)
BEHAT_LOG="./log/behat"
BROWSERTEST_OUTPUT_DIRECTORY="/var/www/logs/phpunit"

# Prinz help
function print_help() {
  echo "usage: $SCRIPT_NAME <action> [options]

  * bootstrap
    --skip-dependencies      # Do not run composer and yarn install
    --skip-install           # Do not run Drupal install (only if arealdy installed)
    --skip-default-content   # Do not load default content
    --skip-styleguide-build  # Do not run yarn build

  * db-reset
    --skip-default-content   # Do not load default content
    --update-dump            # Update database dump (include updated Drupal config)

  * behat
    --skip-reset             # Skip database reset before default content reload
    --help                   # Display behat help
    ...                      # any behat valid args

  * phpunit
    --skip-reset             # Skip database reset before default content reload
    --help                   # Display phpunit help
    ...                      # any phpunit valid args (default: --stop-on-error --stop-on-failure)

  * runserver
    --skip-default-content   # Do not load default content
    --force-reset            # Do not reset database before run server.
    --help                   # Display runserver help
  "
}


# Reset database with dump made before loading default content on bootstrap.
function database_reset() {
  if [ -f $DATABASE_DUMP ]; then
    printf "\e[1;35m* Reset database.\e[0m\n"
  else
    printf "\e[01;31No database dump found, run '$SCRIPT_NAME bootstrap' first.\e[0m\n"
    exit 1
  fi

  # Create database if not exists
  drush sql:create -y

  # Load database dump to reset its state
  $(drush sql:connect) < $DATABASE_DUMP

  # Load Drupal config
  import_drupal_config
}

# Dump database
function database_dump() {
  printf "\e[1;35m* Dump database.\e[0m\n"

  mkdir -p $(dirname $DATABASE_DUMP)
  drush sql-dump --result-file=$DATABASE_DUMP -y
}

# Load default content in database
function enable_default_content() {
  if [ ! -z "$DEFAULT_CONTENT" ] && drush pm-list | grep -q $DEFAULT_CONTENT; then
    printf "\e[1;35m* Run fixtures & default content.\e[0m\n"

    drush pmu default_content $DEFAULT_CONTENT -y
    drush en $DEFAULT_CONTENT -y
  fi
}

# Update swiftmailer config to use host from environment
function enable_mail_host() {
  if [ ! -z "$SMTP_HOST" ] && drush pm-list | grep -q 'swiftmailer'; then
    printf "\e[1;35m* Setup mail host.\e[0m\n"

    drush cset swiftmailer.transport smtp_host "${SMTP_HOST%:*}" -y
    drush cset swiftmailer.transport smtp_port "${SMTP_HOST#*:}" -y
    drush cset swiftmailer.transport smtp_encryption '0' -y
  fi
}

# Import Drupal config
#
# Sometimes Drupal import configs in wrong orders.
# So we repeat the config-import max. 4 times on successives fails.
function import_drupal_config() {
  printf "\e[1;35m* Import drupal configuration.\e[0m\n"

  attempt=0
  until drush config-import -y --source="$CONFIG_DIR"; do
    attempt=$(( attempt+1 ))
    if [ "$attempt" -ge 4 ]; then
      exit 1
    fi
  done

  # Fix Sitename bugged keep display "| Drupal"
  # @see https://www.drupal.org/node/2851877
  drush ev '\Drupal::languageManager()->getLanguageConfigOverrideStorage("fr")->delete("system.site");'

  # Disabling "automated cron"
  drush config-set automated_cron.settings interval 0 -y

  # Rebuild cache
  drush cache-rebuild
}


#
# BOOTSTRAP Drupal
#
if [ "$1" = "bootstrap" ]; then
  shift

  SKIP_DEPENDENCIES=0
  SKIP_INSTALL=0
  SKIP_DEFAULT=0
  SKIP_STYLEGUIDE=0

  while [ $# -gt 0 ]; do
    case "$1" in
      --skip-dependencies)
        SKIP_DEPENDENCIES=1
        ;;
      --skip-install)
        SKIP_INSTALL=1
        ;;
      --skip-default-content)
        SKIP_DEFAULT=1
        ;;
      --skip-styleguide-build)
        SKIP_STYLEGUIDE=1
        ;;
    esac
    shift
  done

  if [ $SKIP_DEPENDENCIES -eq 0 ]; then
    printf "\e[1;35m* Install dependencies.\e[0m\n"

    composer install --no-interaction --prefer-dist --no-suggest
    yarn install --non-interactive
  fi

  if [ $SKIP_INSTALL -eq 0 ] || [ $DRUPAL_INSTALLED -eq 0 ]; then
    (
      set -e

      printf "\e[1;35m* Install Drupal from scratch.\e[0m\n"
      if [ $SKIP_INSTALL -eq 1 ] && [ $DRUPAL_INSTALLED -eq 0 ]; then
        printf "\e[1;35m* (forced beceause not installed).\e[0m\n"
      fi

      # move in web directory
      cd web

      # Install drupal
      drush si standard --db-url=$DATABASE_URL --site-name="$SITE_NAME" --account-name=admin --account-pass=admin --account-mail="admin@example.com" -y

      # Fix rights on settings.php file
      chmod 775 ./sites/default
      chmod 664 --quiet ./sites/default/settings.php || true

      # Fix config directory in settings file
      sed -ri -e "s@\\\$config_directories\['sync'\].+;@\\\$config_directories\['sync'\] = '../config/d8/sync';@g" ./sites/default/settings.php

      # Use DATABASE_URL to populate database config
      echo '$databases["default"]["default"] = \Drupal\Core\Database\Database::convertDbUrlToConnectionInfo(getenv("DATABASE_URL"), DRUPAL_ROOT);' \
        >> ./sites/default/settings.php

      # Remove unwanted content from database that break config import.
      drush ev '\Drupal::entityManager()->getStorage("shortcut_set")->load("default")->delete();'

      # Fix Drupal UUID in database config
      drush config-set system.site uuid "$SITE_UUID" -y

      # Load config
      import_drupal_config

      # Save database dump after install
      database_dump
    )
  else
    printf "\e[1;35m* Skip install Drupal from scratch.\e[0m\n"
  fi

  # Setup usage of private files
  if [ ! -z "$PRIVATE_FILES" ]; then
    printf "\e[1;35m* Setup private files.\e[0m\n"

    mkdir -vp "$PRIVATE_FILES"
    chmod 775 "$PRIVATE_FILES"
    sed -ri -e "s@.+\\\$settings\['file_private_path'\].+;@\\\$settings\['file_private_path'\] = '$PRIVATE_FILES';@g" ./web/sites/default/settings.php
  fi

  # Setup mailer
  enable_mail_host

  # Load default content (then disable module)
  if [ $SKIP_DEFAULT -eq 0 ]; then
    enable_default_content
    drush pmu default_content $DEFAULT_CONTENT -y
  fi

  # Build styleguide assets
  if [ $SKIP_STYLEGUIDE -eq 0 ]; then
    yarn build --production
  fi

#
# RESET DATABASE
#
elif [ "$1" = "db-reset" ]; then
  shift

  SKIP_DEFAULT=0
  UPDATE_DATABASE_DUMP=0

  while [ $# -gt 0 ]; do
    case "$1" in
      --skip-default-content)
        SKIP_DEFAULT=1
        ;;
      --update-dump)
        UPDATE_DATABASE_DUMP=1
        ;;
    esac
    shift
  done

  # Reset database without default content
  database_reset

  # Save database dump after reset (including drupal config update)
  if [ $UPDATE_DATABASE_DUMP -eq 1 ]; then
    database_dump
  fi

  # Load default content (then disable module)
  if [ $SKIP_DEFAULT -eq 0 ]; then
    enable_default_content
    drush pmu default_content $DEFAULT_CONTENT -y
  fi

#
# RUN BEHAT TESTS
#
elif [ "$1" = "runserver" ]; then
  shift

  RUNSERVER_ARGV=""
  SKIP_DEFAULT=0
  FORCE_RESET=0

  while [ $# -gt 0 ]; do
    case "$1" in
      --skip-default-content)
        SKIP_DEFAULT=1
        ;;
      --force-reset)
        FORCE_RESET=1
        ;;
      --help)
        drush runserver --help
        exit $?
        ;;
      *)
        RUNSERVER_ARGV="$RUNSERVER_ARGV $1"
        ;;
    esac
    shift
  done

  if [ $FORCE_RESET -eq 1 ] || [ $DRUPAL_INSTALLED -eq 0 ]; then
    # Reset database
    database_reset

    # Setup mailer (was reset when loaded back config)
    enable_mail_host

    # Load default content (then disable module)
    if [ $SKIP_DEFAULT -eq 0 ]; then
      enable_default_content
      drush pmu default_content $DEFAULT_CONTENT -y
    fi
  fi

  # Run server
  printf "\e[1;35m* Launch test server.\e[0m\n"
  drush runserver $RUNSERVER_ARGV

#
# RUN BEHAT TESTS
#
elif [ "$1" = "behat" ]; then
  shift

  BEHAT_ARGV=""
  SKIP_RESET=0

  while [ $# -gt 0 ]; do
    case "$1" in
      --skip-reset)
        SKIP_RESET=1
        ;;
      --help)
        behat --help
        exit $?
        ;;
      *)
        BEHAT_ARGV="$BEHAT_ARGV $1"
        ;;
    esac
    shift
  done

  if [ $SKIP_RESET -eq 0 ] || [ $DRUPAL_INSTALLED -eq 0 ]; then
    # Reset database
    database_reset

    # Setup mailer (was reset when loaded back config)
    enable_mail_host
  fi

  # Load default content
  enable_default_content

  # Big Pipe cause some block to be rendered with delay and break Behat tests.
  drush pmu big_pipe -y

  # Rebuild Drupal cache
  drush cache-rebuild

  # create log directory
  mkdir -vp $BEHAT_LOG
  chmod -R 777 $BEHAT_LOG

  # Run tests with docker profile
  behat --colors --strict --profile=docker $BEHAT_ARGV
  behat_exit=$?

  # Disable default content
  drush pmu default_content $DEFAULT_CONTENT -y

  # Re-enable Big Pipe.
  drush en big_pipe -y

  # exit
  exit $behat_exit

#
# RUN PHPUNIT TESTS
#
elif [ "$1" = "phpunit" ]; then
  shift

  PHPUNIT_GROUPS=""
  PHPUNIT_EXCLUDE_GROUPS=""
  PHPUNIT_ARGV=""
  SKIP_RESET=0

  while [ $# -gt 0 ]; do
    case "$1" in
      --skip-reset)
        SKIP_RESET=1
        ;;
      --group=*)
        PHPUNIT_GROUPS="$PHPUNIT_GROUPS --group ${1#*=}"
        ;;
      --exclude-group=*)
        PHPUNIT_EXCLUDE_GROUPS="$PHPUNIT_EXCLUDE_GROUPS --exclude-group ${1#*=}"
        ;;
      --help)
        phpunit --help
        exit $?
        ;;
      *)
        PHPUNIT_ARGV="$PHPUNIT_ARGV $1"
        ;;
    esac
    shift
  done

  # Use default group if not in present in arguements
  : ${PHPUNIT_GROUPS:="--group $PHPUNIT_DEFAULT_GROUP"}

  # Set bacl DATABASE_URL to the simpletest db to reset proper database.
  DATABASE_URL=$SIMPLETEST_DB
  export DATABASE_URL

  if [ $SKIP_RESET -eq 0 ] || [ $DRUPAL_INSTALLED -eq 0 ]; then
    # Reset database
    database_reset

    # Setup mailer (was reset when loaded back config)
    enable_mail_host
  fi

  # Ensure log directory exists
  mkdir -vp "$BROWSERTEST_OUTPUT_DIRECTORY"
  chmod -R 777 "$BROWSERTEST_OUTPUT_DIRECTORY"

  # Run tests
  phpunit_exit=0
  (
    cd web

    export SYMFONY_DEPRECATIONS_HELPER
    export SIMPLETEST_DB
    export SIMPLETEST_BASE_URL
    export BROWSERTEST_OUTPUT_DIRECTORY

    phpunit -c core $PHPUNIT_GROUPS $PHPUNIT_EXCLUDE_GROUPS --printer="\Drupal\Tests\Listeners\HtmlOutputPrinter" $PHPUNIT_ARGV
    phpunit_exit=$?
  )

  # exit
  exit $phpunit_exit

#
# COMMAND NOT FOUND
#
else
  [ "$1" = "--help" ] || printf "\e[01;3'$1\` command not found.\e[0m\n\n"
  print_help
  exit 1
fi
