#!/usr/bin/env bash
set -e

# Environement variables
: ${DATABASE_URL:="mysql://root:root@db/drupal"}

: ${TEST_SERVER_PORT:="8888"}

# Script variables
SCRIPT_NAME=$(basename $0)

# Print help
function print_help() {
  echo "usage: $SCRIPT_NAME <action> [options]

  * apache-server

    Run web server using 'apache'. Reset database if not present.

    --with-db-reset          # Reset database before launch server
    --with-default-content   # Load default content (force reset database)
    --cache                  # Do not invalidate opcache (server must be restarted
                             # reload cache)
    --help                   # Display apache help
    -- <...>                 # any apache valid args
  "
}


#
# RUN TEST SERVER
#
if [ "$1" = "apache-server" ]; then
  shift

  TEST_SERVER_CACHE=0
  TEST_SERVER_ARGS=()

  while [ $# -gt 0 ]; do
    case "$1" in
      --cache)
        TEST_SERVER_CACHE=1
        ;;
      *:*)
        TEST_SERVER_PORT=${1#*:}
        ;;
      --help)
        print_help
        apache2-foreground -h
        exit $?
        ;;
      --)
        shift
        TEST_SERVER_ARGS=($@)
        break
        ;;
    esac
    shift
  done

  # Disable opache file timestemps check
  if [ $TEST_SERVER_CACHE -eq 1 ]; then
    echo 'opcache.validate_timestamps=0' >> /usr/local/etc/php/conf.d/opcache-recommended.ini
  fi

  # Run server
  printf "\e[1;35m* Launch test server.\e[0m\n"
  apache2-foreground -c "DocumentRoot $APACHE_DOCUMENT_ROOT" -c "Listen $TEST_SERVER_PORT" ${TEST_SERVER_ARGS[@]}

#
# HELP
#
elif [ "$1" = "--help" ]; then
  print_help
  exit $?

#
# COMMAND NOT FOUND
#
else
  printf "\e[01;35m'$1\` command not found.\e[0m\n\n"
  print_help
  exit 1
fi
