#!/usr/bin/env bash
set -e

cd /var/www/web

DATABASE="mysql://root:root@db/drupal"
NOT_INSTALLED=$(drush sql-query "SELECT * FROM users_field_data where uid = 1" >/dev/null 2>&1 || echo 'yes')

if [ ! -z "$NOT_INSTALLED" ]; then
  drush si standard --db-url=$DATABASE --site-name='Drupal Website' --account-name=admin --account-pass=admin --account-mail=dev@antistatique.net -y

  chmod 775 ./sites/default
  chmod 664 --quiet ./sites/default/{services,settings}.{php,yml} || true

  sed -ri -e "s@config_directories\['sync'\].+;@config_directories\['sync'\] = '../config/d8/sync';@g" ./sites/default/settings.php

  drush ev '\Drupal::entityManager()->getStorage("shortcut_set")->load("default")->delete();'
fi
drush config-set system.site uuid "$(sed -n -e '/uuid:/ s/.*\: *//p' ../config/d8/sync/system.site.yml)" -y

drush cache-rebuild
drush updatedb -y

# Sometimes Drupal 8.4.x import configs in wrong orders.
# So we repeat the config-import max. 3 times on successives fails.
attempt=0
until drush config-import -y --source='../config/d8/sync/'; do
  attempt=$(( attempt+1 ))
  if [ "$attempt" -gt 3 ]; then
    exit 1
  fi
done

drush updatedb -y
drush entity-updates -y
drush cache-rebuild

exit 0
