#!/usr/bin/env bash
set -e

# Environement variables
: ${DATABASE_URL:="mysql://wp:wp@db/wp_development"}

: ${TEST_SERVER_PORT:="8080"}

# Script variables
SCRIPT_NAME=$(basename $0)

# Print help
function print_help() {
  echo "usage: $SCRIPT_NAME <action> [options]

  * bootstrap

    Install wordpress.

  * apache-server

    Run web server using 'apache'.

    --cache                  # Do not invalidate opcache (server must be restarted
                             # to reload cache)
    --help                   # Display apache help
    -- <...>                 # any apache valid args
  "
}

#
# BOOTSTRAP
#
if [ "$1" = "bootstrap" ]; then
  shift

  CMD=""

  while [ $# -gt 0 ]; do
    case "$1" in
      --)
        shift
        CMD=("$@")
        break
        ;;
    esac
    shift
  done

  printf "\e[1;35m* Bootstrap WordPress.\e[0m\n"

  if wp core is-installed --allow-root
  then
    echo "WordPress is already installed, exiting."
    if [ ! -z "$CMD" ]; then
      exec "${CMD[@]}"
    fi
    exit
  fi

  wp core install --allow-root \
    --url="http://localhost:8080" \
    --title="Wordpress" \
    --admin_user="admin" \
    --admin_password="admin" \
    --admin_email="dev@antistatique.net" \
    --skip-email

  wp term update category 1 --allow-root --name="Sample Category"
  wp post delete 1 2 --allow-root

#
# RUN TEST SERVER
#
elif [ "$1" = "apache-server" ]; then
  shift

  TEST_SERVER_CACHE=0
  TEST_SERVER_ARGS=()

  while [ $# -gt 0 ]; do
    case "$1" in
      --cache)
        TEST_SERVER_CACHE=1
        ;;
      *:*)
        TEST_SERVER_PORT=${1#*:}
        ;;
      --help)
        print_help
        apache2-foreground -h
        exit $?
        ;;
      --)
        shift
        TEST_SERVER_ARGS=($@)
        break
        ;;
    esac
    shift
  done

  echo '
<IfModule mod_rewrite.c>
  RewriteEngine On
  RewriteBase /
  RewriteRule ^index\.php$ - [L]
  RewriteCond %{REQUEST_FILENAME} !-f
  RewriteCond %{REQUEST_FILENAME} !-d
  RewriteRule . /index.php [L]
</IfModule>
  ' > /var/www/web/.htaccess

  # Disable opache file timestemps check
  if [ $TEST_SERVER_CACHE -eq 1 ]; then
    echo 'opcache.validate_timestamps=0' >> /usr/local/etc/php/conf.d/opcache-recommended.ini
  fi

  # Update Wordpress setup
  if wp core is-installed --allow-root
  then
    wp plugin activate --allow-root --all
  fi

  # Run server
  printf "\e[1;35m* Launch test server.\e[0m\n"
  apache2-foreground -c "DocumentRoot $APACHE_DOCUMENT_ROOT" -c "Listen $TEST_SERVER_PORT" ${TEST_SERVER_ARGS[@]}

#
# HELP
#
elif [ "$1" = "--help" ]; then
  print_help
  exit $?

#
# COMMAND NOT FOUND
#
else
  printf "\e[01;35m'$1\` command not found.\e[0m\n\n"
  print_help
  exit 1
fi
